# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "TC Casabona"

# A description of your site for meta tag, search engine results.
description: "TC CASABONA"

# A slogan to meet the ambition of the club
slogan: "Un club, une famille, une passion : Bienvenue au TC Casabona"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "http://localhost:4000"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Accueil
    url: /
  - text: Le Club
    url: /club/
  - text: Événements
    url: /evenements/
  - text: Actualités 
    url: /actualites/
  - text: Ten'up
    url: https://tenup.fft.fr/club/67970103

# The shortname for your Disqus site to enable comments.
disqus: 

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Tennis Club Casabona."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
